name: Multi-Platform Build

on:
  workflow_dispatch:

jobs:
  build:
    # strategy and runs-on must be at the same indentation level
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            static_runtime: "ON"
          - os: macos-latest
            static_runtime: "OFF"
          - os: ubuntu-latest
            static_runtime: "ON"

    runs-on: ${{ matrix.os }} # Now it can see matrix.os

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DUSE_STATIC_RUNTIME=${{ matrix.static_runtime }}
